# Generated by Django 4.2.1 on 2023-06-12 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_housing', '0002_housing_price_housing_room_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='type',
        ),
    ]
