# Generated by Django 4.2.1 on 2023-06-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_housing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='housing',
            name='room_area',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roomcount',
            name='count',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
